NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('news.urls')),
    path("accounts/", include("allauth.urls")),
]

NewsPaper/news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import PostList, PostDetail, PostNewsCreate, PostUpdate, PostArticlesCreate, PostDelete, CategoryListView, \
    subscribe, subscriptions

urlpatterns = [

    path('', cache_page(60)(PostList.as_view()), name='post_list'),
    path('<int:pk>', cache_page(60*5)(PostDetail.as_view()), name='post_detail'),
    path('news/create/', PostNewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', PostUpdate.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('articles/create/', PostArticlesCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='articles_update'),
    path('articles/<int:pk>/delete/', PostDelete.as_view(), name='articles_delete'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('subscriptions/<int:pk>', subscribe, name='subscribe'),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPaper/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        post_rating = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += post_rating.get('postRating')

        comment_rating = self.user.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += comment_rating.get('commentRating')

        self.rating = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True)

    def get_category(self):
        return self.name

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category_type = models.CharField(max_length=50)
    time_create = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, blank=True, through='PostCategory', related_name='category')
    title = models.CharField(max_length=255)
    text = models.TextField(default='Здесь могла быть статья')
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        s = str(self.text)
        if len(s) <= 124:
            return s
        else:
            return "%s..." % (s[:124])

    def __str__(self):
        return f'{self.title.title()}: {self.author}'

    def get_absolute_url(self):
        return f'/{self.id}'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(default='Комментарий')
    time_create = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.user.title()}: {self.post}'


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

NewsPaper/templates/category.html
{% extends 'flatpages/default.html' %}

{% block title %}
News
{% endblock title %}

{% block content %}

    {% if category.id %}
    <div class="subscribe">
        <em>
            Subscribe to
            <strong>{{ category }}?</strong>
        </em>
        <a href="{#% url 'news:subscribe' category.id %#}" class="button button-outline">
            Subscribe
        </a>
    </div>
    {% endif %}

    {% include "news/inc/posts.html "%}

{% endblock content %}

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Новости</h1>
   <h3>Всего новостей:  {{ posts|length|default_if_none:"0" }}</h3>

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id%}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}

   <hr>

   {% if category_news_list %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Краткий текст</td>
           </tr>

           {% for post in category_news_list %}
           <tr>
               <td>{{ post.title|censor }}</td>
               <td>{{ post.time_create|date:'d M Y' }}</td>
               <td>{{ post.text|truncatewords:20|censor }}</td>
               <td>
                   {%for category in post.category.all %}
                    <a href="{% url 'category_list' category.id %}">{{ category }} </a>
                   {% endfor %}
               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Нет новостей</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

{{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h2>Здравствуй! Новые статьи за неделю</h2>
  <ul>
    {% for post in posts %}
      <li><a href="{{ link }}{{ post.get_absolute_url }}">{{post.title}}</a></li>
    {% endfor %}
  </ul>
</body>
</html>

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    <h1>{{ post.title|censor }}</h1>
    <h5>{{ post.time_create|date:'d M Y' }}</h5>
    <h4>{{ post.text|censor}}</h4>
    <hr>
    {%for category in post.category.all %}
        <h4> <a href="{% url 'category_list' category.id %}">{{ category }} </a> </h4>
    {% endfor %}
{% endblock content %}

NewsPaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Новая <a href = {{ link }}>статья </a></h2>
    <p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Новости</h1>
   <h3>Всего новостей:  {{ posts|length|default_if_none:"0" }}</h3>

   <form action="" method="get">
       {{ filterset.form.as_p }}

       <input type="submit" value="Найти" />
   </form>

   <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'news_create' %}">Добавить новость</a>
    <hr>
    <a href="{% url 'articles_create' %}">Добавить статью</a>
    {% endif %}

   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Краткий текст</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title|censor }}</td>
               <td>{{ post.time_create|date:'d M Y' }}</td>
               <td>{{ post.text|truncatewords:20|censor }}</td>

                               <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'news_update' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'post_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Нет новостей</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

{{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
  <h1 class="text-center">{{ message }}{{ category }}</h1>
{% endblock content %}

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}